name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual run

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: SailajaDas
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
          svg_out_path: dist/github-snake.svg
          svg_out_path_dark: dist/github-snake-dark.svg

      - name: Push the generated snake.svg to the output branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
          directory: dist
